sudo: required
services:
  - docker

before_install:
  - docker build -t agkhalil/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true agkhalil/react-test npm test

after_success:
  - docker build -t agkhalil/multi-client ./client
  - docker build -t agkhalil/multi-nginx ./nginx
  - docker build -t agkhalil/multi-server ./server
  - docker build -t agkhalil/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and uplod to DockerHub
  - docker push agkhalil/multi-client
  - docker push agkhalil/multi-nginx
  - docker push agkhalil/multi-server
  - docker push agkhalil/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-770245323416
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY